[package]
name = "bevy_scene_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6.1"
bevy_editor_pls = { git = "https://github.com/jakobhellermann/bevy_editor_pls"}